#!/bin/bash
# Quick deploy script for Render.com

echo "================================================"
echo "  Ganesh Donations API - Deploy Helper"
echo "================================================"
echo ""
echo "This script will help you deploy to Render.com"
echo ""
echo "Prerequisites:"
echo "  ✓ Render.com account (free)"
echo "  ✓ GitHub account"
echo "  ✓ Git installed"
echo ""
echo "Steps:"
echo ""
echo "1. Initialize Git (if not done):"
echo "   git init"
echo ""
echo "2. Add all files:"
echo "   git add ."
echo ""
echo "3. Commit:"
echo "   git commit -m 'Deploy to Render'"
echo ""
echo "4. Create GitHub repo and push:"
echo "   # Create repo at github.com/new"
echo "   git remote add origin https://github.com/YOUR_USERNAME/ganesh-donations.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "5. Deploy on Render:"
echo "   a. Go to https://dashboard.render.com"
echo "   b. Click 'New +' → 'Blueprint'"
echo "   c. Connect your GitHub repo"
echo "   d. Select your repository"
echo "   e. Render will auto-detect render.yaml"
echo "   f. Click 'Apply'"
echo ""
echo "6. Wait 3-5 minutes for deployment"
echo ""
echo "7. Copy your API URL (looks like):"
echo "   https://ganesh-donations-api.onrender.com"
echo ""
echo "8. Update Flutter app with new URL"
echo ""
echo "================================================"
